title: "Geo-SfM Course"
logo: ./content/assets/logo.gif
author: Peter Betlem, Nil Rodes and Contributors
copyright: "2023 (CC-BY-NC except where otherwise stated)"

repository:
  url: https://github.com/UNISvalbard/Geo-SfM
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  use_edit_page_button: true
  announcement: 'Found this tutorial helpful? Please Star me! [![GitHub Repo stars](https://img.shields.io/github/stars/UNISvalbard/Geo-SfM)](https://github.com/UNISvalbard/Geo-SfM)'
  comments:
    hypothesis: true
  extra_path: ["slides"]

execute:
  execute_notebooks: "auto"

parse:
  myst_extended_syntax: true
  myst_header_anchors: 4

launch_buttons:
  binderhub_url: ""


only_build_toc_files: true

parse:
#  myst_extended_syntax: true
  myst_header_anchors: 4

bibtex_bibfiles:
  - content/lessons/about/zreferences.bib

sphinx:
  config:
    #bibtex_reference_style: author_year
    bibtex_default_style: alpha